[package]
name = "oxychat"
version = "0.1.0"
authors = ["Dominod <dev@dominod.fr>"]
edition = "2018"

[[bin]]
bench = false
path = "src/bin/main.rs"
name = "oxychat"

[dependencies]
reqwest = { version = "0.10", features = ["json", "blocking"] }
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }

[dependencies.cursive]
version = "0.15"
default-features = false
features = ["toml", "ncurses-backend"]
