refresh_rate: 30 seconds
appenders:
  stdout:
    kind: console
  file:
    kind: file
    path: "/tmp/talkoxid.log"
    # encoder:
    #   pattern: "{d} - {m}{n}"
root:
  level: info
  appenders:
    - file
